# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Projects"
  identifier="All Projects"
  url = "#projects"
  weight = 15

[[main]]
name = "Virtual Reality"
parent = "All Projects"
url = "/virtual-reality"
weight = 14

[[main]]
name = "Data Science"
parent = "All Projects"
url = "/project/ncaaf-coaches"
weight = 15

[[main]]
name = "Brain Imaging"
parent = "All Projects"
url = "/project/fitviz"
weight = 16

[[main]]
name = "Clinical Research"
parent = "All Projects"
url = "/project/neuroflow"
weight = 17

[[main]]
  name = "Skills"
  url = "#skills"
  weight = 20

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 25

[[main]]
  name = "Blog"
  url = "blog"
  weight = 30

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
   name = "CV"
   url = "files/cv.pdf"
   weight = 35
